services:
  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "${ANALYTICS_SERVICE_PORT:-8120}:8120"
    environment:
      # App
      APP_ENV: ${APP_ENV:-development}

      # MySQL
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}

      # MongoDB
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
        mysql-db:
            condition: service_healthy
            restart: true
        mongo-db:
            condition: service_healthy
            restart: true

networks:
  app-network:
    external: true